/**
 * 获取门店智能检索返回的门店列表
 * @constructor
 */
export function GetStoreIntelligentSearchList(values) {
    return new Promise((resolve => {
        resolve({
            result: {
                total: 1,
                everyPage: 1,
                currentPage: 1,
                result: [
                    {
                        spShopId: 348,
                        name: "047测试门店"
                    },
                    {
                        spShopId: 349,
                        name: "xh测试门店"
                    },
                    {
                        spShopId: 350,
                        name: "cbr测试门店"
                    },
                    {
                        spShopId: 351,
                        name: "wy门店"
                    },
                    {
                        spShopId: 352,
                        name: "上海测试门店"
                    },
                    {
                        spShopId: 353,
                        name: "通知测试账户1"
                    },
                    {
                        spShopId: 354,
                        name: "Justin"
                    },
                    {
                        spShopId: 355,
                        name: "zcp"
                    },
                    {
                        spShopId: 356,
                        name: "Eden"
                    },
                    {
                        spShopId: 357,
                        name: "lcb"
                    },
                    {
                        spShopId: 358,
                        name: "xzs测试"
                    },
                    {
                        spShopId: 359,
                        name: "wl测试门店"
                    },
                    {
                        spShopId: 360,
                        name: "yj001"
                    },
                    {
                        spShopId: 361,
                        name: "qtools888"
                    },
                    {
                        spShopId: 362,
                        name: "lcb22"
                    },
                    {
                        spShopId: 363,
                        name: "海涛测试门店"
                    }
                ]
            },
            httpCode: "0",
            message: null,
            fileDomain: "https://qtltestfiles.oss-cn-shanghai.aliyuncs.com/",
            sessionId: "81B6EBCEA3EEFA15FAD81BCB7037E52A"
        })
    }))
}

/**
 * 获取门店成本数据列表
 * @constructor
 */
export function GetCostOfStoreDataList(values) {
    return new Promise((resolve => {
        resolve({
            result: {
                total: 1,
                everyPage: 1,
                currentPage: 1,
                result: [
                    {
                        spShopId: null,
                        shopName: "047测试门店",
                        url: "/apps/qerp/v6/apache-tomcat-8.0.44/bin/./tempPath/rpShopCostMonth_20200301-001500053OhvL8YmF7X.xlsx",
                        time: "2020-02"
                    },
                    {
                        spShopId: null,
                        shopName: "xh测试门店",
                        url: "/apps/qerp/v6/apache-tomcat-8.0.44/bin/./tempPath/rpShopCostMonth_20200301-001504447KR9bOOSBA8.xlsx",
                        time: "2020-02"
                    },
                    {
                        spShopId: null,
                        shopName: "cbr测试门店",
                        url: "/apps/qerp/v6/apache-tomcat-8.0.44/bin/./tempPath/rpShopCostMonth_20200301-001504556T9LVJMenuM.xlsx",
                        time: "2020-02"
                    },
                    {
                        spShopId: null,
                        shopName: "wy门店",
                        url: "/apps/qerp/v6/apache-tomcat-8.0.44/bin/./tempPath/rpShopCostMonth_20200301-001504600P71i2KCgRw.xlsx",
                        time: "2020-02"
                    },
                    {
                        spShopId: null,
                        shopName: "上海测试门店",
                        url: "/apps/qerp/v6/apache-tomcat-8.0.44/bin/./tempPath/rpShopCostMonth_20200301-001504646XrC0qj2yBh.xlsx",
                        time: "2020-02"
                    },
                    {
                        spShopId: null,
                        shopName: "通知测试账户1",
                        url: "/apps/qerp/v6/apache-tomcat-8.0.44/bin/./tempPath/rpShopCostMonth_20200301-001504688hFdf9CKtTN.xlsx",
                        time: "2020-02"
                    },
                    {
                        spShopId: null,
                        shopName: "Justin",
                        url: "/apps/qerp/v6/apache-tomcat-8.0.44/bin/./tempPath/rpShopCostMonth_20200301-001504717HzcQXoJUPQ.xlsx",
                        time: "2020-02"
                    },
                    {
                        spShopId: null,
                        shopName: "zcp",
                        url: "/apps/qerp/v6/apache-tomcat-8.0.44/bin/./tempPath/rpShopCostMonth_20200301-001504735Nkuss5sgE7.xlsx",
                        time: "2020-02"
                    },
                    {
                        spShopId: null,
                        shopName: "Eden",
                        url: "/apps/qerp/v6/apache-tomcat-8.0.44/bin/./tempPath/rpShopCostMonth_20200301-00150477276mVw7IiOW.xlsx",
                        time: "2020-02"
                    },
                    {
                        spShopId: null,
                        shopName: "lcb",
                        url: "/apps/qerp/v6/apache-tomcat-8.0.44/bin/./tempPath/rpShopCostMonth_20200301-001504808UD1I5zgXXr.xlsx",
                        time: "2020-02"
                    },
                    {
                        spShopId: null,
                        shopName: "xzs测试",
                        url: "/apps/qerp/v6/apache-tomcat-8.0.44/bin/./tempPath/rpShopCostMonth_20200301-001504834UlnHO3oOhO.xlsx",
                        time: "2020-02"
                    },
                    {
                        spShopId: null,
                        shopName: "wl测试门店",
                        url: "/apps/qerp/v6/apache-tomcat-8.0.44/bin/./tempPath/rpShopCostMonth_20200301-001504870EB3VLAmuiH.xlsx",
                        time: "2020-02"
                    },
                    {
                        spShopId: null,
                        shopName: "yj001",
                        url: "/apps/qerp/v6/apache-tomcat-8.0.44/bin/./tempPath/rpShopCostMonth_20200301-0015048947BuLH93z6f.xlsx",
                        time: "2020-02"
                    },
                    {
                        spShopId: null,
                        shopName: "qtools888",
                        url: "/apps/qerp/v6/apache-tomcat-8.0.44/bin/./tempPath/rpShopCostMonth_20200301-001504921uKrxJYUQt6.xlsx",
                        time: "2020-02"
                    },
                    {
                        spShopId: null,
                        shopName: "lcb22",
                        url: "/apps/qerp/v6/apache-tomcat-8.0.44/bin/./tempPath/rpShopCostMonth_20200301-001504944hjA6dR7yg6.xlsx",
                        time: "2020-02"
                    }
                ]
            },
            httpCode: "0",
            message: null,
            fileDomain: "https://qtltestfiles.oss-cn-shanghai.aliyuncs.com/",
            sessionId: "81B6EBCEA3EEFA15FAD81BCB7037E52A"
        })
    }))
}

/**
 * 获取成本核算数据列表
 * @constructor
 */
export function GetCostAccountingDataList(values) {
    return new Promise((resolve => {
        resolve({
            result: {
                total: 1,
                everyPage: 1,
                currentPage: 1,
                result: [
                    {
                        name: "2020年3月成本核算数据",
                        url: "",
                        warn: "4月1日生成数据",
                        preSellUrl: "",
                        preSellwarn: "4月1日预售商品生成数据"
                    }
                ]
            },
            httpCode: "0",
            message: null,
            fileDomain: "https://qtltestfiles.oss-cn-shanghai.aliyuncs.com/",
            sessionId: "81B6EBCEA3EEFA15FAD81BCB7037E52A"
        })
    }))
}

/**
 * 获取采购到货数据列表
 * @constructor
 */
export function GetPurchasingTheArrivalOfTheGoodsDataList(values) {
    return new Promise((resolve => {
        resolve({
            result: {
                total: 1,
                everyPage: 1,
                currentPage: 1,
                result: [
                    {
                        supplierName: "xh供应商",
                        receivedAmount: "9161.00",
                        leftAmount: null,
                        receivedQty: 10837,
                        leftQty: null,
                        completedOrderQty: null,
                        receivingOrderQty: null,
                        waitingOrderQty: null
                    },
                    {
                        supplierName: "047供应商",
                        receivedAmount: "183.30",
                        leftAmount: null,
                        receivedQty: 4341,
                        leftQty: null,
                        completedOrderQty: null,
                        receivingOrderQty: null,
                        waitingOrderQty: null
                    },
                    {
                        supplierName: "cbr供应商",
                        receivedAmount: "5689.00",
                        leftAmount: null,
                        receivedQty: 1500,
                        leftQty: null,
                        completedOrderQty: null,
                        receivingOrderQty: null,
                        waitingOrderQty: null
                    }
                ]
            },
            httpCode: "0",
            message: null,
            fileDomain: "https://qtltestfiles.oss-cn-shanghai.aliyuncs.com/",
            sessionId: "81B6EBCEA3EEFA15FAD81BCB7037E52A"
        })
    }))
}

/**
 * 获取门店发票数据列表
 * @constructor
 */
export function GetStoresTheInvoiceList(values) {
    return new Promise((resolve => {
        resolve({
            result: {
                total: 1,
                everyPage: 1,
                currentPage: 1,
                result: {
                    shopdatas: [
                        {
                            name: "047测试门店",
                            amount: "0",
                            returnAmount: "0",
                            cancelAmount: "0",
                            cancelQty: 0,
                            returnQty: 0,
                            qty: 0,
                            salesSumQty: null,
                            refundSumQty: 0,
                            categoryAmounts: [
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0"
                            ],
                            qtys: null,
                            url: "/apps/qerp/v6/apache-tomcat-8.0.44/bin/./tempPath/spPurchaseInvoice_20200301-002000035i1grVHXl76.xlsx",
                            time: "2020-02"
                        },
                        {
                            name: "xh测试门店",
                            amount: "0",
                            returnAmount: "0",
                            cancelAmount: "0",
                            cancelQty: 0,
                            returnQty: 0,
                            qty: 0,
                            salesSumQty: null,
                            refundSumQty: 0,
                            categoryAmounts: [
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0"
                            ],
                            qtys: null,
                            url: "/apps/qerp/v6/apache-tomcat-8.0.44/bin/./tempPath/spPurchaseInvoice_20200301-002000135cca1wXA4pr.xlsx",
                            time: "2020-02"
                        },
                        {
                            name: "cbr测试门店",
                            amount: "0",
                            returnAmount: "0",
                            cancelAmount: "0",
                            cancelQty: 0,
                            returnQty: 0,
                            qty: 0,
                            salesSumQty: null,
                            refundSumQty: 0,
                            categoryAmounts: [
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0"
                            ],
                            qtys: null,
                            url: "/apps/qerp/v6/apache-tomcat-8.0.44/bin/./tempPath/spPurchaseInvoice_20200301-002000187XXNWwut795.xlsx",
                            time: "2020-02"
                        },
                        {
                            name: "wy门店",
                            amount: "0",
                            returnAmount: "0",
                            cancelAmount: "0",
                            cancelQty: 0,
                            returnQty: 0,
                            qty: 0,
                            salesSumQty: null,
                            refundSumQty: 0,
                            categoryAmounts: [
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0"
                            ],
                            qtys: null,
                            url: "/apps/qerp/v6/apache-tomcat-8.0.44/bin/./tempPath/spPurchaseInvoice_20200301-0020002317DbmTg9Ys5.xlsx",
                            time: "2020-02"
                        },
                        {
                            name: "上海测试门店",
                            amount: "0",
                            returnAmount: "0",
                            cancelAmount: "0",
                            cancelQty: 0,
                            returnQty: 0,
                            qty: 0,
                            salesSumQty: null,
                            refundSumQty: 0,
                            categoryAmounts: [
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0"
                            ],
                            qtys: null,
                            url: "/apps/qerp/v6/apache-tomcat-8.0.44/bin/./tempPath/spPurchaseInvoice_20200301-002000267HPJqbgTnhc.xlsx",
                            time: "2020-02"
                        },
                        {
                            name: "通知测试账户1",
                            amount: "0",
                            returnAmount: "0",
                            cancelAmount: "0",
                            cancelQty: 0,
                            returnQty: 0,
                            qty: 0,
                            salesSumQty: null,
                            refundSumQty: 0,
                            categoryAmounts: [
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0"
                            ],
                            qtys: null,
                            url: "/apps/qerp/v6/apache-tomcat-8.0.44/bin/./tempPath/spPurchaseInvoice_20200301-002000299gyLazWlPpP.xlsx",
                            time: "2020-02"
                        },
                        {
                            name: "Justin",
                            amount: "0",
                            returnAmount: "0",
                            cancelAmount: "0",
                            cancelQty: 0,
                            returnQty: 0,
                            qty: 0,
                            salesSumQty: null,
                            refundSumQty: 0,
                            categoryAmounts: [
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0"
                            ],
                            qtys: null,
                            url: "/apps/qerp/v6/apache-tomcat-8.0.44/bin/./tempPath/spPurchaseInvoice_20200301-002000349n3cIffmem9.xlsx",
                            time: "2020-02"
                        },
                        {
                            name: "zcp",
                            amount: "0",
                            returnAmount: "0",
                            cancelAmount: "0",
                            cancelQty: 0,
                            returnQty: 0,
                            qty: 0,
                            salesSumQty: null,
                            refundSumQty: 0,
                            categoryAmounts: [
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0"
                            ],
                            qtys: null,
                            url: "/apps/qerp/v6/apache-tomcat-8.0.44/bin/./tempPath/spPurchaseInvoice_20200301-002000375vGbc6RXtmv.xlsx",
                            time: "2020-02"
                        },
                        {
                            name: "Eden",
                            amount: "0",
                            returnAmount: "0",
                            cancelAmount: "0",
                            cancelQty: 0,
                            returnQty: 0,
                            qty: 0,
                            salesSumQty: null,
                            refundSumQty: 0,
                            categoryAmounts: [
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0"
                            ],
                            qtys: null,
                            url: "/apps/qerp/v6/apache-tomcat-8.0.44/bin/./tempPath/spPurchaseInvoice_20200301-002000395mrbEJohB4w.xlsx",
                            time: "2020-02"
                        },
                        {
                            name: "lcb",
                            amount: "0",
                            returnAmount: "0",
                            cancelAmount: "0",
                            cancelQty: 0,
                            returnQty: 0,
                            qty: 0,
                            salesSumQty: null,
                            refundSumQty: 0,
                            categoryAmounts: [
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0"
                            ],
                            tys: null,
                            rl: "/apps/qerp/v6/apache-tomcat-8.0.44/bin/./tempPath/spPurchaseInvoice_20200301-002000420XYlWNrIxor.xlsx",
                            ime: "2020-02"
                        },
                        {
                            ame: "xzs测试",
                            mount: "0",
                            eturnAmount: "0",
                            ancelAmount: "0",
                            ancelQty: 0,
                            eturnQty: 0,
                            ty: 0,
                            alesSumQty: null,
                            efundSumQty: 0,
                            ategoryAmounts: [
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0"
                            ],
                            tys: null,
                            rl: "/apps/qerp/v6/apache-tomcat-8.0.44/bin/./tempPath/spPurchaseInvoice_20200301-002000449mN1zihK8yv.xlsx",
                            ime: "2020-02"
                        },
                        {
                            ame: "wl测试门店",
                            mount: "0",
                            eturnAmount: "0",
                            ancelAmount: "0",
                            ancelQty: 0,
                            eturnQty: 0,
                            ty: 0,
                            alesSumQty: null,
                            efundSumQty: 0,
                            ategoryAmounts: [
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0"
                            ],
                            tys: null,
                            rl: "/apps/qerp/v6/apache-tomcat-8.0.44/bin/./tempPath/spPurchaseInvoice_20200301-002000467kLo4J7l1IU.xlsx",
                            ime: "2020-02"
                        },
                        {
                            ame: "yj001",
                            mount: "0",
                            eturnAmount: "0",
                            ancelAmount: "0",
                            ancelQty: 0,
                            eturnQty: 0,
                            ty: 0,
                            alesSumQty: null,
                            efundSumQty: 0,
                            ategoryAmounts: [
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0"
                            ],
                            tys: null,
                            rl: "/apps/qerp/v6/apache-tomcat-8.0.44/bin/./tempPath/spPurchaseInvoice_20200301-002000496EZIzajmi8p.xlsx",
                            ime: "2020-02"
                        },
                        {
                            ame: "qtools888",
                            mount: "0",
                            eturnAmount: "0",
                            ancelAmount: "0",
                            ancelQty: 0,
                            eturnQty: 0,
                            ty: 0,
                            alesSumQty: null,
                            efundSumQty: 0,
                            ategoryAmounts: [
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0"
                            ],
                            tys: null,
                            rl: "/apps/qerp/v6/apache-tomcat-8.0.44/bin/./tempPath/spPurchaseInvoice_20200301-0020005126NeUKS9tSK.xlsx",
                            ime: "2020-02"
                        },
                        {
                            ame: "lcb22",
                            mount: "0",
                            eturnAmount: "0",
                            ancelAmount: "0",
                            ancelQty: 0,
                            eturnQty: 0,
                            ty: 0,
                            alesSumQty: null,
                            efundSumQty: 0,
                            ategoryAmounts: [
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0",
                                "0"
                            ],
                            tys: null,
                            rl: "/apps/qerp/v6/apache-tomcat-8.0.44/bin/./tempPath/spPurchaseInvoice_20200301-002000554odZDbkiJ6e.xlsx",
                            ime: "2020-02"
                        }
                    ],
                    categoryNames: [
                        "洗护用品",
                        "数量",
                        "居家生活",
                        "数量",
                        "婴幼玩具",
                        "数量",
                        "其他",
                        "数量",
                        "奶粉辅食",
                        "数量",
                        "安全出行",
                        "数量",
                        "日常穿搭",
                        "数量",
                        "妈妈专区",
                        "数量",
                        "居家日用",
                        "数量",
                        "安全出行",
                        "数量",
                        "营养辅食",
                        "数量",
                        "喂哺用品",
                        "数量",
                        "孕产系列",
                        "数量",
                        "尿裤湿巾",
                        "数量",
                        "日常穿搭",
                        "数量",
                        "居家生活",
                        "数量",
                        "尿裤湿巾",
                        "数量",
                        "安全出行",
                        "数量",
                        "孕产系列",
                        "数量",
                        "婴幼玩具",
                        "数量",
                        "奶粉辅食",
                        "数量",
                        "喂哺用品",
                        "数量",
                        "其他",
                        "数量",
                        "洗护用品",
                        "数量",
                        "纸尿裤",
                        "数量",
                        "进口奶粉",
                        "数量",
                        "宝宝洗护",
                        "数量",
                        "宝宝洗护",
                        "数量",
                        "宝宝食品",
                        "数量",
                        "宝宝出行",
                        "数量",
                        "赠品",
                        "数量",
                        "床品",
                        "数量",
                        "孕妈用品",
                        "数量",
                        "居家生活",
                        "数量",
                        "服饰",
                        "数量",
                        "餐具喂养",
                        "数量",
                        "宝宝玩具",
                        "数量",
                        "尿布湿",
                        "数量",
                        "清洁消毒",
                        "数量",
                        "文具",
                        "数量",
                        "亲子",
                        "数量",
                        "宝宝产品",
                        "数量",
                        "辅料",
                        "数量",
                        "尿不湿",
                        "数量",
                        "营养品",
                        "数量",
                        "礼盒",
                        "数量",
                        "凉鞋",
                        "数量",
                        "帆布鞋",
                        "数量",
                        "鞋类",
                        "数量",
                        "大件",
                        "数量",
                        "物料",
                        "数量"
                    ]
                }
            },
            httpCode: "0",
            message: null,
            fileDomain: "https://qtltestfiles.oss-cn-shanghai.aliyuncs.com/",
            sessionId: "81B6EBCEA3EEFA15FAD81BCB7037E52A"
        })
    }))
}
