/**
 * 获取门店订单数据基础数据
 * @constructor
 */
export function GetStoreOrderData() {
    return {
        shopOrderData: {
            rpOrderDataId: null,
            rpDateTime: null,
            rpDate: null,
            qtySum: 0,
            validQtySum: 0,
            preSellQtySum: 0,
            deQtySum: 0,
            cancelQtySum: 0,
            amountSum: "0",
            validAmountSum: "0",
            preSellAmountSum: "0",
            deAmountSum: "0",
            cancelAmountSum: "0",
            rpDateStr: null,
            upQtySum: 0,
            upPreSellQtySum: 0,
            upDeQtySum: 0,
            upCancelQtySum: 0,
            upValidQtySum: 0,
            upAmountSum: "0",
            upPreSellAmountSum: "0",
            upDeAmountSum: "0",
            upCancelAmountSum: "0",
            upValidAmountSum: "0",
            upQtyMom: 0.0,
            upPreSellQtyMom: 0.0,
            upDeQtyMom: 0.0,
            upCancelQtyMom: 0.0,
            upValidQtyMom: 0.0,
            upAmountMom: 0.0,
            upPreSellAmountMom: 0.0,
            upDeAmountMom: 0.0,
            upCancelAmountMom: 0.0,
            upValidAmountMom: 0.0,
            updateTime: "2020/03/16 17:57"
        },
        code: "0",
        message: null,
        fileDomain: "https://qtltestfiles.oss-cn-shanghai.aliyuncs.com/",
        sessionId: "3EDAEA917DEC86B6A25688966A4A0369"
    }
}

/**
 * 获取门店订单图表数据
 * @param values 请求参数
 * @constructor
 */
export function GetStoreChartsData(values) {
    return {
        shopOrderDatas: [
            {
                rpOrderDataId: null,
                rpDateTime: null,
                rpDate: "03.15",
                qtySum: 0,
                validQtySum: null,
                preSellQtySum: null,
                deQtySum: null,
                cancelQtySum: null,
                amountSum: "0",
                validAmountSum: null,
                preSellAmountSum: null,
                deAmountSum: null,
                cancelAmountSum: null,
                rpDateStr: null,
                upQtySum: null,
                upPreSellQtySum: null,
                upDeQtySum: null,
                upCancelQtySum: null,
                upValidQtySum: null,
                upAmountSum: null,
                upPreSellAmountSum: null,
                upDeAmountSum: null,
                upCancelAmountSum: null,
                upValidAmountSum: null,
                upQtyMom: 0.0,
                upPreSellQtyMom: 0.0,
                upDeQtyMom: 0.0,
                upCancelQtyMom: 0.0,
                upValidQtyMom: 0.0,
                upAmountMom: 0.0,
                upPreSellAmountMom: 0.0,
                upDeAmountMom: 0.0,
                upCancelAmountMom: 0.0,
                upValidAmountMom: 0.0,
                updateTime: null
            },
            {
                rpOrderDataId: null,
                rpDateTime: null,
                rpDate: "03.16",
                qtySum: 11,
                validQtySum: null,
                preSellQtySum: null,
                deQtySum: null,
                cancelQtySum: null,
                amountSum: "6949.00",
                validAmountSum: null,
                preSellAmountSum: null,
                deAmountSum: null,
                cancelAmountSum: null,
                rpDateStr: null,
                upQtySum: null,
                upPreSellQtySum: null,
                upDeQtySum: null,
                upCancelQtySum: null,
                upValidQtySum: null,
                upAmountSum: null,
                upPreSellAmountSum: null,
                upDeAmountSum: null,
                upCancelAmountSum: null,
                upValidAmountSum: null,
                upQtyMom: 0.0,
                upPreSellQtyMom: 0.0,
                upDeQtyMom: 0.0,
                upCancelQtyMom: 0.0,
                upValidQtyMom: 0.0,
                upAmountMom: 0.0,
                upPreSellAmountMom: 0.0,
                upDeAmountMom: 0.0,
                upCancelAmountMom: 0.0,
                upValidAmountMom: 0.0,
                updateTime: null
            },
            {
                rpOrderDataId: null,
                rpDateTime: null,
                rpDate: "03.17",
                qtySum: 0,
                validQtySum: null,
                preSellQtySum: null,
                deQtySum: null,
                cancelQtySum: null,
                amountSum: "0",
                validAmountSum: null,
                preSellAmountSum: null,
                deAmountSum: null,
                cancelAmountSum: null,
                rpDateStr: null,
                upQtySum: null,
                upPreSellQtySum: null,
                upDeQtySum: null,
                upCancelQtySum: null,
                upValidQtySum: null,
                upAmountSum: null,
                upPreSellAmountSum: null,
                upDeAmountSum: null,
                upCancelAmountSum: null,
                upValidAmountSum: null,
                upQtyMom: 0.0,
                upPreSellQtyMom: 0.0,
                upDeQtyMom: 0.0,
                upCancelQtyMom: 0.0,
                upValidQtyMom: 0.0,
                upAmountMom: 0.0,
                upPreSellAmountMom: 0.0,
                upDeAmountMom: 0.0,
                upCancelAmountMom: 0.0,
                upValidAmountMom: 0.0,
                updateTime: null
            },
            {
                rpOrderDataId: null,
                rpDateTime: null,
                rpDate: "03.18",
                qtySum: 0,
                validQtySum: null,
                preSellQtySum: null,
                deQtySum: null,
                cancelQtySum: null,
                amountSum: "0",
                validAmountSum: null,
                preSellAmountSum: null,
                deAmountSum: null,
                cancelAmountSum: null,
                rpDateStr: null,
                upQtySum: null,
                upPreSellQtySum: null,
                upDeQtySum: null,
                upCancelQtySum: null,
                upValidQtySum: null,
                upAmountSum: null,
                upPreSellAmountSum: null,
                upDeAmountSum: null,
                upCancelAmountSum: null,
                upValidAmountSum: null,
                upQtyMom: 0.0,
                upPreSellQtyMom: 0.0,
                upDeQtyMom: 0.0,
                upCancelQtyMom: 0.0,
                upValidQtyMom: 0.0,
                upAmountMom: 0.0,
                upPreSellAmountMom: 0.0,
                upDeAmountMom: 0.0,
                upCancelAmountMom: 0.0,
                upValidAmountMom: 0.0,
                updateTime: null
            },
            {
                rpOrderDataId: null,
                rpDateTime: null,
                rpDate: "03.19",
                qtySum: 0,
                validQtySum: null,
                preSellQtySum: null,
                deQtySum: null,
                cancelQtySum: null,
                amountSum: "0",
                validAmountSum: null,
                preSellAmountSum: null,
                deAmountSum: null,
                cancelAmountSum: null,
                rpDateStr: null,
                upQtySum: null,
                upPreSellQtySum: null,
                upDeQtySum: null,
                upCancelQtySum: null,
                upValidQtySum: null,
                upAmountSum: null,
                upPreSellAmountSum: null,
                upDeAmountSum: null,
                upCancelAmountSum: null,
                upValidAmountSum: null,
                upQtyMom: 0.0,
                upPreSellQtyMom: 0.0,
                upDeQtyMom: 0.0,
                upCancelQtyMom: 0.0,
                upValidQtyMom: 0.0,
                upAmountMom: 0.0,
                upPreSellAmountMom: 0.0,
                upDeAmountMom: 0.0,
                upCancelAmountMom: 0.0,
                upValidAmountMom: 0.0,
                updateTime: null
            },
            {
                rpOrderDataId: null,
                rpDateTime: null,
                rpDate: "03.20",
                qtySum: 0,
                validQtySum: null,
                preSellQtySum: null,
                deQtySum: null,
                cancelQtySum: null,
                amountSum: "0",
                validAmountSum: null,
                preSellAmountSum: null,
                deAmountSum: null,
                cancelAmountSum: null,
                rpDateStr: null,
                upQtySum: null,
                upPreSellQtySum: null,
                upDeQtySum: null,
                upCancelQtySum: null,
                upValidQtySum: null,
                upAmountSum: null,
                upPreSellAmountSum: null,
                upDeAmountSum: null,
                upCancelAmountSum: null,
                upValidAmountSum: null,
                upQtyMom: 0.0,
                upPreSellQtyMom: 0.0,
                upDeQtyMom: 0.0,
                upCancelQtyMom: 0.0,
                upValidQtyMom: 0.0,
                upAmountMom: 0.0,
                upPreSellAmountMom: 0.0,
                upDeAmountMom: 0.0,
                upCancelAmountMom: 0.0,
                upValidAmountMom: 0.0,
                updateTime: null
            },
            {
                rpOrderDataId: null,
                rpDateTime: null,
                rpDate: "03.21",
                qtySum: 0,
                validQtySum: null,
                preSellQtySum: null,
                deQtySum: null,
                cancelQtySum: null,
                amountSum: "0",
                validAmountSum: null,
                preSellAmountSum: null,
                deAmountSum: null,
                cancelAmountSum: null,
                rpDateStr: null,
                upQtySum: null,
                upPreSellQtySum: null,
                upDeQtySum: null,
                upCancelQtySum: null,
                upValidQtySum: null,
                upAmountSum: null,
                upPreSellAmountSum: null,
                upDeAmountSum: null,
                upCancelAmountSum: null,
                upValidAmountSum: null,
                upQtyMom: 0.0,
                upPreSellQtyMom: 0.0,
                upDeQtyMom: 0.0,
                upCancelQtyMom: 0.0,
                upValidQtyMom: 0.0,
                upAmountMom: 0.0,
                upPreSellAmountMom: 0.0,
                upDeAmountMom: 0.0,
                upCancelAmountMom: 0.0,
                upValidAmountMom: 0.0,
                updateTime: null
            }
        ],
        code: "0",
        message: null,
        fileDomain: "https://qtltestfiles.oss-cn-shanghai.aliyuncs.com/",
        sessionId: "6CED6C0054BB9F4F60C027172C4E030F"
    }
}

/**
 * 获取门店订单表格数据列表
 * @param values 筛选参数
 * @constructor
 */
export function GetStoreTableDataList(values) {
    return {
        rpShopOrderDatas: [
            {
                rpOrderDataId: null,
                rpDateTime: null,
                rpDate: "20200316",
                qtySum: 11,
                validQtySum: null,
                preSellQtySum: 0,
                deQtySum: 0,
                cancelQtySum: 11,
                amountSum: "6949.00",
                validAmountSum: null,
                preSellAmountSum: "0.00",
                deAmountSum: "0.00",
                cancelAmountSum: "6949.00",
                rpDateStr: null,
                upQtySum: null,
                upPreSellQtySum: null,
                upDeQtySum: null,
                upCancelQtySum: null,
                upValidQtySum: null,
                upAmountSum: null,
                upPreSellAmountSum: null,
                upDeAmountSum: null,
                upCancelAmountSum: null,
                upValidAmountSum: null,
                upQtyMom: 0.0,
                upPreSellQtyMom: 0.0,
                upDeQtyMom: 0.0,
                upCancelQtyMom: 0.0,
                upValidQtyMom: 0.0,
                upAmountMom: 0.0,
                upPreSellAmountMom: 0.0,
                upDeAmountMom: 0.0,
                upCancelAmountMom: 0.0,
                upValidAmountMom: 0.0,
                updateTime: null
            }
        ],
        code: "0",
        message: null,
        fileDomain: "https://qtltestfiles.oss-cn-shanghai.aliyuncs.com/",
        sessionId: "6CED6C0054BB9F4F60C027172C4E030F"
    }
}


/**
 * 获取Pos订单数据基础数据
 * @constructor
 */
export function GetPosOrderData() {
    return {
        posOrderData: {
            rpPosOrderdataId: null,
            rpDateTime: null,
            rpDate: null,
            shopId: null,
            orderQtySum: 0,
            mbCardQtySum: 0,
            chargeQtySum: 0,
            returnQtySum: 0,
            amount: "0",
            mbCardAmount: "0",
            chargeAmount: "0",
            returnAmount: "0",
            saleAmount: "0",
            rpDateStr: null,
            rpDateTimeStr: null,
            upOrderQtySum: 0,
            upMbCardQtySum: 0,
            upChargeQtySum: 0,
            upReturnQtySum: 0,
            upAmount: "0",
            upMbCardAmount: "0",
            upChargeAmount: "0",
            upReturnAmount: "0",
            upSaleAmount: "0",
            upOrderQtySumMom: 0.0,
            upMbCardQtySumMom: 0.0,
            upChargeQtySumMom: 0.0,
            upReturnQtySumMom: 0.0,
            upAmountMom: 0.0,
            upMbCardAmountMom: 0.0,
            upChargeAmountMom: 0.0,
            upReturnAmountMom: 0.0,
            upSaleAmountMom: 0.0,
            updateTime: "2020/03/16 17:57"
        },
        code: "0",
        message: null,
        fileDomain: "https://qtltestfiles.oss-cn-shanghai.aliyuncs.com/",
        sessionId: "6CED6C0054BB9F4F60C027172C4E030F"
    }
}

/**
 * 获取Pos订单图表数据
 * @param values 请求参数
 * @constructor
 */
export function GetPosChartsData(values) {
    return {
        posOrderDatas: [
            {
                rpPosOrderdataId: null,
                rpDateTime: null,
                rpDate: null,
                shopId: null,
                orderQtySum: 0,
                mbCardQtySum: null,
                chargeQtySum: null,
                returnQtySum: null,
                amount: "0",
                mbCardAmount: null,
                chargeAmount: null,
                returnAmount: null,
                saleAmount: null,
                rpDateStr: "03.15",
                rpDateTimeStr: null,
                upOrderQtySum: null,
                upMbCardQtySum: null,
                upChargeQtySum: null,
                upReturnQtySum: null,
                upAmount: null,
                upMbCardAmount: null,
                upChargeAmount: null,
                upReturnAmount: null,
                upSaleAmount: null,
                upOrderQtySumMom: 0.0,
                upMbCardQtySumMom: 0.0,
                upChargeQtySumMom: 0.0,
                upReturnQtySumMom: 0.0,
                upAmountMom: 0.0,
                upMbCardAmountMom: 0.0,
                upChargeAmountMom: 0.0,
                upReturnAmountMom: 0.0,
                upSaleAmountMom: 0.0,
                updateTime: null
            },
            {
                rpPosOrderdataId: null,
                rpDateTime: null,
                rpDate: null,
                shopId: null,
                orderQtySum: 0,
                mbCardQtySum: null,
                chargeQtySum: null,
                returnQtySum: null,
                amount: "0",
                mbCardAmount: null,
                chargeAmount: null,
                returnAmount: null,
                saleAmount: null,
                rpDateStr: "03.16",
                rpDateTimeStr: null,
                upOrderQtySum: null,
                upMbCardQtySum: null,
                upChargeQtySum: null,
                upReturnQtySum: null,
                upAmount: null,
                upMbCardAmount: null,
                upChargeAmount: null,
                upReturnAmount: null,
                upSaleAmount: null,
                upOrderQtySumMom: 0.0,
                upMbCardQtySumMom: 0.0,
                upChargeQtySumMom: 0.0,
                upReturnQtySumMom: 0.0,
                upAmountMom: 0.0,
                upMbCardAmountMom: 0.0,
                upChargeAmountMom: 0.0,
                upReturnAmountMom: 0.0,
                upSaleAmountMom: 0.0,
                updateTime: null
            },
            {
                rpPosOrderdataId: null,
                rpDateTime: null,
                rpDate: null,
                shopId: null,
                orderQtySum: 0,
                mbCardQtySum: null,
                chargeQtySum: null,
                returnQtySum: null,
                amount: "0",
                mbCardAmount: null,
                chargeAmount: null,
                returnAmount: null,
                saleAmount: null,
                rpDateStr: "03.17",
                rpDateTimeStr: null,
                upOrderQtySum: null,
                upMbCardQtySum: null,
                upChargeQtySum: null,
                upReturnQtySum: null,
                upAmount: null,
                upMbCardAmount: null,
                upChargeAmount: null,
                upReturnAmount: null,
                upSaleAmount: null,
                upOrderQtySumMom: 0.0,
                upMbCardQtySumMom: 0.0,
                upChargeQtySumMom: 0.0,
                upReturnQtySumMom: 0.0,
                upAmountMom: 0.0,
                upMbCardAmountMom: 0.0,
                upChargeAmountMom: 0.0,
                upReturnAmountMom: 0.0,
                upSaleAmountMom: 0.0,
                updateTime: null
            },
            {
                rpPosOrderdataId: null,
                rpDateTime: null,
                rpDate: null,
                shopId: null,
                orderQtySum: 0,
                mbCardQtySum: null,
                chargeQtySum: null,
                returnQtySum: null,
                amount: "0",
                mbCardAmount: null,
                chargeAmount: null,
                returnAmount: null,
                saleAmount: null,
                rpDateStr: "03.18",
                rpDateTimeStr: null,
                upOrderQtySum: null,
                upMbCardQtySum: null,
                upChargeQtySum: null,
                upReturnQtySum: null,
                upAmount: null,
                upMbCardAmount: null,
                upChargeAmount: null,
                upReturnAmount: null,
                upSaleAmount: null,
                upOrderQtySumMom: 0.0,
                upMbCardQtySumMom: 0.0,
                upChargeQtySumMom: 0.0,
                upReturnQtySumMom: 0.0,
                upAmountMom: 0.0,
                upMbCardAmountMom: 0.0,
                upChargeAmountMom: 0.0,
                upReturnAmountMom: 0.0,
                upSaleAmountMom: 0.0,
                updateTime: null
            },
            {
                rpPosOrderdataId: null,
                rpDateTime: null,
                rpDate: null,
                shopId: null,
                orderQtySum: 0,
                mbCardQtySum: null,
                chargeQtySum: null,
                returnQtySum: null,
                amount: "0",
                mbCardAmount: null,
                chargeAmount: null,
                returnAmount: null,
                saleAmount: null,
                rpDateStr: "03.19",
                rpDateTimeStr: null,
                upOrderQtySum: null,
                upMbCardQtySum: null,
                upChargeQtySum: null,
                upReturnQtySum: null,
                upAmount: null,
                upMbCardAmount: null,
                upChargeAmount: null,
                upReturnAmount: null,
                upSaleAmount: null,
                upOrderQtySumMom: 0.0,
                upMbCardQtySumMom: 0.0,
                upChargeQtySumMom: 0.0,
                upReturnQtySumMom: 0.0,
                upAmountMom: 0.0,
                upMbCardAmountMom: 0.0,
                upChargeAmountMom: 0.0,
                upReturnAmountMom: 0.0,
                upSaleAmountMom: 0.0,
                updateTime: null
            },
            {
                rpPosOrderdataId: null,
                rpDateTime: null,
                rpDate: null,
                shopId: null,
                orderQtySum: 0,
                mbCardQtySum: null,
                chargeQtySum: null,
                returnQtySum: null,
                amount: "0",
                mbCardAmount: null,
                chargeAmount: null,
                returnAmount: null,
                saleAmount: null,
                rpDateStr: "03.20",
                rpDateTimeStr: null,
                upOrderQtySum: null,
                upMbCardQtySum: null,
                upChargeQtySum: null,
                upReturnQtySum: null,
                upAmount: null,
                upMbCardAmount: null,
                upChargeAmount: null,
                upReturnAmount: null,
                upSaleAmount: null,
                upOrderQtySumMom: 0.0,
                upMbCardQtySumMom: 0.0,
                upChargeQtySumMom: 0.0,
                upReturnQtySumMom: 0.0,
                upAmountMom: 0.0,
                upMbCardAmountMom: 0.0,
                upChargeAmountMom: 0.0,
                upReturnAmountMom: 0.0,
                upSaleAmountMom: 0.0,
                updateTime: null
            },
            {
                rpPosOrderdataId: null,
                rpDateTime: null,
                rpDate: null,
                shopId: null,
                orderQtySum: 0,
                mbCardQtySum: null,
                chargeQtySum: null,
                returnQtySum: null,
                amount: "0",
                mbCardAmount: null,
                chargeAmount: null,
                returnAmount: null,
                saleAmount: null,
                rpDateStr: "03.21",
                rpDateTimeStr: null,
                upOrderQtySum: null,
                upMbCardQtySum: null,
                upChargeQtySum: null,
                upReturnQtySum: null,
                upAmount: null,
                upMbCardAmount: null,
                upChargeAmount: null,
                upReturnAmount: null,
                upSaleAmount: null,
                upOrderQtySumMom: 0.0,
                upMbCardQtySumMom: 0.0,
                upChargeQtySumMom: 0.0,
                upReturnQtySumMom: 0.0,
                upAmountMom: 0.0,
                upMbCardAmountMom: 0.0,
                upChargeAmountMom: 0.0,
                upReturnAmountMom: 0.0,
                upSaleAmountMom: 0.0,
                updateTime: null
            }
        ],
        code: "0",
        message: null,
        fileDomain: "https://qtltestfiles.oss-cn-shanghai.aliyuncs.com/",
        sessionId: "6CED6C0054BB9F4F60C027172C4E030F"
    }
}

/**
 * 获取Pos订单表格数据列表
 * @param values 筛选参数
 * @constructor
 */
export function GetPosTableDataList(values) {
    return {
        posOrderDatas: [],
        code: "0",
        message: null,
        fileDomain: "https://qtltestfiles.oss-cn-shanghai.aliyuncs.com/",
        sessionId: "6CED6C0054BB9F4F60C027172C4E030F"
    }
}
