/**
 * 获取门店销售基础数据
 * @constructor
 */
export function GetStoreSaleBaseData() {
    return new Promise((resolve => {
        resolve({
            result: {
                rpShopSaleDataId: null,
                rpDateTime: null,
                rpDate: null,
                shopId: null,
                qbyQty: null,
                qbyAmount: null,
                qbyCancelAmount: null,
                qbyCancelQty: null,
                qbyReturnQty: null,
                qbyReturnAmount: null,
                posReturnQty: null,
                posReturnAmount: null,
                posQty: null,
                posAmount: "0.00",
                sumCostAmount: null,
                sumReturnCostAmount: null,
                cleanAmount: "0.00",
                saleAmount: "0.00",
                updateTime: "",
                rpDateStr: null,
                no: null,
                name: null,
                noOrder: null,
                saleRatio: null,
                yesterdayAmount: "0.00",
                yesterdayCostAmount: "0.00",
                upPosAmount: "0.00",
                upSaleAmount: "0.00",
                upCleanAmount: "0.00",
                upYesterdayAmount: "0.00",
                upYesterdayCostAmount: "0.00",
                shopRank: 10,
                studyShop: 0,
                guidanceShop: 1,
                carefulShop: 6
            },
            httpCode: "0",
            message: null,
            fileDomain: "https://qtltestfiles.oss-cn-shanghai.aliyuncs.com/",
            sessionId: "81B6EBCEA3EEFA15FAD81BCB7037E52A"
        })
    }))
}

/**
 * 获取门店销售图表数据
 * @constructor
 */
export function GetStoreSaleChartsData() {
    return new Promise((resolve => {
        resolve({
            result: {
                total: 1,
                everyPage: 1,
                currentPage: 1,
                result: [
                    {
                        rpShopSaleDataId: null,
                        rpDateTime: "00:00",
                        rpDate: null,
                        shopId: null,
                        qbyQty: 0,
                        qbyAmount: "0",
                        qbyCancelAmount: null,
                        qbyCancelQty: null,
                        qbyReturnQty: null,
                        qbyReturnAmount: null,
                        posReturnQty: null,
                        posReturnAmount: null,
                        posQty: 0,
                        posAmount: "0",
                        sumCostAmount: null,
                        sumReturnCostAmount: null,
                        cleanAmount: null,
                        saleAmount: null,
                        updateTime: null,
                        rpDateStr: "2020-02-22",
                        no: null,
                        name: null,
                        noOrder: null,
                        saleRatio: null,
                        yesterdayAmount: null,
                        yesterdayCostAmount: null,
                        upPosAmount: null,
                        upSaleAmount: null,
                        upCleanAmount: null,
                        upYesterdayAmount: null,
                        upYesterdayCostAmount: null,
                        shopRank: null,
                        studyShop: null,
                        guidanceShop: null,
                        carefulShop: null
                    },
                    {
                        rpShopSaleDataId: null,
                        rpDateTime: "01:00",
                        rpDate: null,
                        shopId: null,
                        qbyQty: 0,
                        qbyAmount: "0",
                        qbyCancelAmount: null,
                        qbyCancelQty: null,
                        qbyReturnQty: null,
                        qbyReturnAmount: null,
                        posReturnQty: null,
                        posReturnAmount: null,
                        posQty: 0,
                        posAmount: "0",
                        sumCostAmount: null,
                        sumReturnCostAmount: null,
                        cleanAmount: null,
                        saleAmount: null,
                        updateTime: null,
                        rpDateStr: "2020-02-22",
                        no: null,
                        name: null,
                        noOrder: null,
                        saleRatio: null,
                        yesterdayAmount: null,
                        yesterdayCostAmount: null,
                        upPosAmount: null,
                        upSaleAmount: null,
                        upCleanAmount: null,
                        upYesterdayAmount: null,
                        upYesterdayCostAmount: null,
                        shopRank: null,
                        studyShop: null,
                        guidanceShop: null,
                        carefulShop: null
                    },
                    {
                        rpShopSaleDataId: null,
                        rpDateTime: "02:00",
                        rpDate: null,
                        shopId: null,
                        qbyQty: 0,
                        qbyAmount: "0",
                        qbyCancelAmount: null,
                        qbyCancelQty: null,
                        qbyReturnQty: null,
                        qbyReturnAmount: null,
                        posReturnQty: null,
                        posReturnAmount: null,
                        posQty: 0,
                        posAmount: "0",
                        sumCostAmount: null,
                        sumReturnCostAmount: null,
                        cleanAmount: null,
                        saleAmount: null,
                        updateTime: null,
                        rpDateStr: "2020-02-22",
                        no: null,
                        name: null,
                        noOrder: null,
                        saleRatio: null,
                        yesterdayAmount: null,
                        yesterdayCostAmount: null,
                        upPosAmount: null,
                        upSaleAmount: null,
                        upCleanAmount: null,
                        upYesterdayAmount: null,
                        upYesterdayCostAmount: null,
                        shopRank: null,
                        studyShop: null,
                        guidanceShop: null,
                        carefulShop: null
                    },
                    {
                        rpShopSaleDataId: null,
                        rpDateTime: "03:00",
                        rpDate: null,
                        shopId: null,
                        qbyQty: 0,
                        qbyAmount: "0",
                        qbyCancelAmount: null,
                        qbyCancelQty: null,
                        qbyReturnQty: null,
                        qbyReturnAmount: null,
                        posReturnQty: null,
                        posReturnAmount: null,
                        posQty: 0,
                        posAmount: "0",
                        sumCostAmount: null,
                        sumReturnCostAmount: null,
                        cleanAmount: null,
                        saleAmount: null,
                        updateTime: null,
                        rpDateStr: "2020-02-22",
                        no: null,
                        name: null,
                        noOrder: null,
                        saleRatio: null,
                        yesterdayAmount: null,
                        yesterdayCostAmount: null,
                        upPosAmount: null,
                        upSaleAmount: null,
                        upCleanAmount: null,
                        upYesterdayAmount: null,
                        upYesterdayCostAmount: null,
                        shopRank: null,
                        studyShop: null,
                        guidanceShop: null,
                        carefulShop: null
                    },
                    {
                        rpShopSaleDataId: null,
                        rpDateTime: "04:00",
                        rpDate: null,
                        shopId: null,
                        qbyQty: 0,
                        qbyAmount: "0",
                        qbyCancelAmount: null,
                        qbyCancelQty: null,
                        qbyReturnQty: null,
                        qbyReturnAmount: null,
                        posReturnQty: null,
                        posReturnAmount: null,
                        posQty: 0,
                        posAmount: "0",
                        sumCostAmount: null,
                        sumReturnCostAmount: null,
                        cleanAmount: null,
                        saleAmount: null,
                        updateTime: null,
                        rpDateStr: "2020-02-22",
                        no: null,
                        name: null,
                        noOrder: null,
                        saleRatio: null,
                        yesterdayAmount: null,
                        yesterdayCostAmount: null,
                        upPosAmount: null,
                        upSaleAmount: null,
                        upCleanAmount: null,
                        upYesterdayAmount: null,
                        upYesterdayCostAmount: null,
                        shopRank: null,
                        studyShop: null,
                        guidanceShop: null,
                        carefulShop: null
                    },
                    {
                        rpShopSaleDataId: null,
                        rpDateTime: "05:00",
                        rpDate: null,
                        shopId: null,
                        qbyQty: 0,
                        qbyAmount: "0",
                        qbyCancelAmount: null,
                        qbyCancelQty: null,
                        qbyReturnQty: null,
                        qbyReturnAmount: null,
                        posReturnQty: null,
                        posReturnAmount: null,
                        posQty: 0,
                        posAmount: "0",
                        sumCostAmount: null,
                        sumReturnCostAmount: null,
                        cleanAmount: null,
                        saleAmount: null,
                        updateTime: null,
                        rpDateStr: "2020-02-22",
                        no: null,
                        name: null,
                        noOrder: null,
                        saleRatio: null,
                        yesterdayAmount: null,
                        yesterdayCostAmount: null,
                        upPosAmount: null,
                        upSaleAmount: null,
                        upCleanAmount: null,
                        upYesterdayAmount: null,
                        upYesterdayCostAmount: null,
                        shopRank: null,
                        studyShop: null,
                        guidanceShop: null,
                        carefulShop: null
                    },
                    {
                        rpShopSaleDataId: null,
                        rpDateTime: "06:00",
                        rpDate: null,
                        shopId: null,
                        qbyQty: 0,
                        qbyAmount: "0",
                        qbyCancelAmount: null,
                        qbyCancelQty: null,
                        qbyReturnQty: null,
                        qbyReturnAmount: null,
                        posReturnQty: null,
                        posReturnAmount: null,
                        posQty: 0,
                        posAmount: "0",
                        sumCostAmount: null,
                        sumReturnCostAmount: null,
                        cleanAmount: null,
                        saleAmount: null,
                        updateTime: null,
                        rpDateStr: "2020-02-22",
                        no: null,
                        name: null,
                        noOrder: null,
                        saleRatio: null,
                        yesterdayAmount: null,
                        yesterdayCostAmount: null,
                        upPosAmount: null,
                        upSaleAmount: null,
                        upCleanAmount: null,
                        upYesterdayAmount: null,
                        upYesterdayCostAmount: null,
                        shopRank: null,
                        studyShop: null,
                        guidanceShop: null,
                        carefulShop: null
                    },
                    {
                        rpShopSaleDataId: null,
                        rpDateTime: "07:00",
                        rpDate: null,
                        shopId: null,
                        qbyQty: 0,
                        qbyAmount: "0",
                        qbyCancelAmount: null,
                        qbyCancelQty: null,
                        qbyReturnQty: null,
                        qbyReturnAmount: null,
                        posReturnQty: null,
                        posReturnAmount: null,
                        posQty: 0,
                        posAmount: "0",
                        sumCostAmount: null,
                        sumReturnCostAmount: null,
                        cleanAmount: null,
                        saleAmount: null,
                        updateTime: null,
                        rpDateStr: "2020-02-22",
                        no: null,
                        name: null,
                        noOrder: null,
                        saleRatio: null,
                        yesterdayAmount: null,
                        yesterdayCostAmount: null,
                        upPosAmount: null,
                        upSaleAmount: null,
                        upCleanAmount: null,
                        upYesterdayAmount: null,
                        upYesterdayCostAmount: null,
                        shopRank: null,
                        studyShop: null,
                        guidanceShop: null,
                        carefulShop: null
                    },
                    {
                        rpShopSaleDataId: null,
                        rpDateTime: "08:00",
                        rpDate: null,
                        shopId: null,
                        qbyQty: 0,
                        qbyAmount: "0",
                        qbyCancelAmount: null,
                        qbyCancelQty: null,
                        qbyReturnQty: null,
                        qbyReturnAmount: null,
                        posReturnQty: null,
                        posReturnAmount: null,
                        posQty: 0,
                        posAmount: "0",
                        sumCostAmount: null,
                        sumReturnCostAmount: null,
                        cleanAmount: null,
                        saleAmount: null,
                        updateTime: null,
                        rpDateStr: "2020-02-22",
                        no: null,
                        name: null,
                        noOrder: null,
                        saleRatio: null,
                        yesterdayAmount: null,
                        yesterdayCostAmount: null,
                        upPosAmount: null,
                        upSaleAmount: null,
                        upCleanAmount: null,
                        upYesterdayAmount: null,
                        upYesterdayCostAmount: null,
                        shopRank: null,
                        studyShop: null,
                        guidanceShop: null,
                        carefulShop: null
                    },
                    {
                        rpShopSaleDataId: null,
                        rpDateTime: "09:00",
                        rpDate: null,
                        shopId: null,
                        qbyQty: 0,
                        qbyAmount: "0",
                        qbyCancelAmount: null,
                        qbyCancelQty: null,
                        qbyReturnQty: null,
                        qbyReturnAmount: null,
                        posReturnQty: null,
                        posReturnAmount: null,
                        posQty: 0,
                        posAmount: "0",
                        sumCostAmount: null,
                        sumReturnCostAmount: null,
                        cleanAmount: null,
                        saleAmount: null,
                        updateTime: null,
                        rpDateStr: "2020-02-22",
                        no: null,
                        name: null,
                        noOrder: null,
                        saleRatio: null,
                        yesterdayAmount: null,
                        yesterdayCostAmount: null,
                        upPosAmount: null,
                        upSaleAmount: null,
                        upCleanAmount: null,
                        upYesterdayAmount: null,
                        upYesterdayCostAmount: null,
                        shopRank: null,
                        studyShop: null,
                        guidanceShop: null,
                        carefulShop: null
                    },
                    {
                        rpShopSaleDataId: null,
                        rpDateTime: "10:00",
                        rpDate: null,
                        shopId: null,
                        qbyQty: 0,
                        qbyAmount: "0",
                        qbyCancelAmount: null,
                        qbyCancelQty: null,
                        qbyReturnQty: null,
                        qbyReturnAmount: null,
                        posReturnQty: null,
                        posReturnAmount: null,
                        posQty: 0,
                        posAmount: "0",
                        sumCostAmount: null,
                        sumReturnCostAmount: null,
                        cleanAmount: null,
                        saleAmount: null,
                        updateTime: null,
                        rpDateStr: "2020-02-22",
                        no: null,
                        name: null,
                        noOrder: null,
                        saleRatio: null,
                        yesterdayAmount: null,
                        yesterdayCostAmount: null,
                        upPosAmount: null,
                        upSaleAmount: null,
                        upCleanAmount: null,
                        upYesterdayAmount: null,
                        upYesterdayCostAmount: null,
                        shopRank: null,
                        studyShop: null,
                        guidanceShop: null,
                        carefulShop: null
                    },
                    {
                        rpShopSaleDataId: null,
                        rpDateTime: "11:00",
                        rpDate: null,
                        shopId: null,
                        qbyQty: 0,
                        qbyAmount: "0",
                        qbyCancelAmount: null,
                        qbyCancelQty: null,
                        qbyReturnQty: null,
                        qbyReturnAmount: null,
                        posReturnQty: null,
                        posReturnAmount: null,
                        posQty: 0,
                        posAmount: "0",
                        sumCostAmount: null,
                        sumReturnCostAmount: null,
                        cleanAmount: null,
                        saleAmount: null,
                        updateTime: null,
                        rpDateStr: "2020-02-22",
                        no: null,
                        name: null,
                        noOrder: null,
                        saleRatio: null,
                        yesterdayAmount: null,
                        yesterdayCostAmount: null,
                        upPosAmount: null,
                        upSaleAmount: null,
                        upCleanAmount: null,
                        upYesterdayAmount: null,
                        upYesterdayCostAmount: null,
                        shopRank: null,
                        studyShop: null,
                        guidanceShop: null,
                        carefulShop: null
                    },
                    {
                        rpShopSaleDataId: null,
                        rpDateTime: "12:00",
                        rpDate: null,
                        shopId: null,
                        qbyQty: 0,
                        qbyAmount: "0",
                        qbyCancelAmount: null,
                        qbyCancelQty: null,
                        qbyReturnQty: null,
                        qbyReturnAmount: null,
                        posReturnQty: null,
                        posReturnAmount: null,
                        posQty: 0,
                        posAmount: "0",
                        sumCostAmount: null,
                        sumReturnCostAmount: null,
                        cleanAmount: null,
                        saleAmount: null,
                        updateTime: null,
                        rpDateStr: "2020-02-22",
                        no: null,
                        name: null,
                        noOrder: null,
                        saleRatio: null,
                        yesterdayAmount: null,
                        yesterdayCostAmount: null,
                        upPosAmount: null,
                        upSaleAmount: null,
                        upCleanAmount: null,
                        upYesterdayAmount: null,
                        upYesterdayCostAmount: null,
                        shopRank: null,
                        studyShop: null,
                        guidanceShop: null,
                        carefulShop: null
                    },
                    {
                        rpShopSaleDataId: null,
                        rpDateTime: "13:00",
                        rpDate: null,
                        shopId: null,
                        qbyQty: 0,
                        qbyAmount: "0",
                        qbyCancelAmount: null,
                        qbyCancelQty: null,
                        qbyReturnQty: null,
                        qbyReturnAmount: null,
                        posReturnQty: null,
                        posReturnAmount: null,
                        posQty: 0,
                        posAmount: "0",
                        sumCostAmount: null,
                        sumReturnCostAmount: null,
                        cleanAmount: null,
                        saleAmount: null,
                        updateTime: null,
                        rpDateStr: "2020-02-22",
                        no: null,
                        name: null,
                        noOrder: null,
                        saleRatio: null,
                        yesterdayAmount: null,
                        yesterdayCostAmount: null,
                        upPosAmount: null,
                        upSaleAmount: null,
                        upCleanAmount: null,
                        upYesterdayAmount: null,
                        upYesterdayCostAmount: null,
                        shopRank: null,
                        studyShop: null,
                        guidanceShop: null,
                        carefulShop: null
                    },
                    {
                        rpShopSaleDataId: null,
                        rpDateTime: "14:00",
                        rpDate: null,
                        shopId: null,
                        qbyQty: 0,
                        qbyAmount: "0",
                        qbyCancelAmount: null,
                        qbyCancelQty: null,
                        qbyReturnQty: null,
                        qbyReturnAmount: null,
                        posReturnQty: null,
                        posReturnAmount: null,
                        posQty: 0,
                        posAmount: "0",
                        sumCostAmount: null,
                        sumReturnCostAmount: null,
                        cleanAmount: null,
                        saleAmount: null,
                        updateTime: null,
                        rpDateStr: "2020-02-22",
                        no: null,
                        name: null,
                        noOrder: null,
                        saleRatio: null,
                        yesterdayAmount: null,
                        yesterdayCostAmount: null,
                        upPosAmount: null,
                        upSaleAmount: null,
                        upCleanAmount: null,
                        upYesterdayAmount: null,
                        upYesterdayCostAmount: null,
                        shopRank: null,
                        studyShop: null,
                        guidanceShop: null,
                        carefulShop: null
                    },
                    {
                        rpShopSaleDataId: null,
                        rpDateTime: "15:00",
                        rpDate: null,
                        shopId: null,
                        qbyQty: 0,
                        qbyAmount: "0",
                        qbyCancelAmount: null,
                        qbyCancelQty: null,
                        qbyReturnQty: null,
                        qbyReturnAmount: null,
                        posReturnQty: null,
                        posReturnAmount: null,
                        posQty: 0,
                        posAmount: "0",
                        sumCostAmount: null,
                        sumReturnCostAmount: null,
                        cleanAmount: null,
                        saleAmount: null,
                        updateTime: null,
                        rpDateStr: "2020-02-22",
                        no: null,
                        name: null,
                        noOrder: null,
                        saleRatio: null,
                        yesterdayAmount: null,
                        yesterdayCostAmount: null,
                        upPosAmount: null,
                        upSaleAmount: null,
                        upCleanAmount: null,
                        upYesterdayAmount: null,
                        upYesterdayCostAmount: null,
                        shopRank: null,
                        studyShop: null,
                        guidanceShop: null,
                        carefulShop: null
                    },
                    {
                        rpShopSaleDataId: null,
                        rpDateTime: "16:00",
                        rpDate: null,
                        shopId: null,
                        qbyQty: 0,
                        qbyAmount: "0",
                        qbyCancelAmount: null,
                        qbyCancelQty: null,
                        qbyReturnQty: null,
                        qbyReturnAmount: null,
                        posReturnQty: null,
                        posReturnAmount: null,
                        posQty: 0,
                        posAmount: "0",
                        sumCostAmount: null,
                        sumReturnCostAmount: null,
                        cleanAmount: null,
                        saleAmount: null,
                        updateTime: null,
                        rpDateStr: "2020-02-22",
                        no: null,
                        name: null,
                        noOrder: null,
                        saleRatio: null,
                        yesterdayAmount: null,
                        yesterdayCostAmount: null,
                        upPosAmount: null,
                        upSaleAmount: null,
                        upCleanAmount: null,
                        upYesterdayAmount: null,
                        upYesterdayCostAmount: null,
                        shopRank: null,
                        studyShop: null,
                        guidanceShop: null,
                        carefulShop: null
                    },
                    {
                        rpShopSaleDataId: null,
                        rpDateTime: "17:00",
                        rpDate: null,
                        shopId: null,
                        qbyQty: 0,
                        qbyAmount: "0",
                        qbyCancelAmount: null,
                        qbyCancelQty: null,
                        qbyReturnQty: null,
                        qbyReturnAmount: null,
                        posReturnQty: null,
                        posReturnAmount: null,
                        posQty: 0,
                        posAmount: "0",
                        sumCostAmount: null,
                        sumReturnCostAmount: null,
                        cleanAmount: null,
                        saleAmount: null,
                        updateTime: null,
                        rpDateStr: "2020-02-22",
                        no: null,
                        name: null,
                        noOrder: null,
                        saleRatio: null,
                        yesterdayAmount: null,
                        yesterdayCostAmount: null,
                        upPosAmount: null,
                        upSaleAmount: null,
                        upCleanAmount: null,
                        upYesterdayAmount: null,
                        upYesterdayCostAmount: null,
                        shopRank: null,
                        studyShop: null,
                        guidanceShop: null,
                        carefulShop: null
                    },
                    {
                        rpShopSaleDataId: null,
                        rpDateTime: "18:00",
                        rpDate: null,
                        shopId: null,
                        qbyQty: 0,
                        qbyAmount: "0",
                        qbyCancelAmount: null,
                        qbyCancelQty: null,
                        qbyReturnQty: null,
                        qbyReturnAmount: null,
                        posReturnQty: null,
                        posReturnAmount: null,
                        posQty: 0,
                        posAmount: "0",
                        sumCostAmount: null,
                        sumReturnCostAmount: null,
                        cleanAmount: null,
                        saleAmount: null,
                        updateTime: null,
                        rpDateStr: "2020-02-22",
                        no: null,
                        name: null,
                        noOrder: null,
                        saleRatio: null,
                        yesterdayAmount: null,
                        yesterdayCostAmount: null,
                        upPosAmount: null,
                        upSaleAmount: null,
                        upCleanAmount: null,
                        upYesterdayAmount: null,
                        upYesterdayCostAmount: null,
                        shopRank: null,
                        studyShop: null,
                        guidanceShop: null,
                        carefulShop: null
                    },
                    {
                        rpShopSaleDataId: null,
                        rpDateTime: "19:00",
                        rpDate: null,
                        shopId: null,
                        qbyQty: 0,
                        qbyAmount: "0",
                        qbyCancelAmount: null,
                        qbyCancelQty: null,
                        qbyReturnQty: null,
                        qbyReturnAmount: null,
                        posReturnQty: null,
                        posReturnAmount: null,
                        posQty: 0,
                        posAmount: "0",
                        sumCostAmount: null,
                        sumReturnCostAmount: null,
                        cleanAmount: null,
                        saleAmount: null,
                        updateTime: null,
                        rpDateStr: "2020-02-22",
                        no: null,
                        name: null,
                        noOrder: null,
                        saleRatio: null,
                        yesterdayAmount: null,
                        yesterdayCostAmount: null,
                        upPosAmount: null,
                        upSaleAmount: null,
                        upCleanAmount: null,
                        upYesterdayAmount: null,
                        upYesterdayCostAmount: null,
                        shopRank: null,
                        studyShop: null,
                        guidanceShop: null,
                        carefulShop: null
                    },
                    {
                        rpShopSaleDataId: null,
                        rpDateTime: "20:00",
                        rpDate: null,
                        shopId: null,
                        qbyQty: 0,
                        qbyAmount: "0",
                        qbyCancelAmount: null,
                        qbyCancelQty: null,
                        qbyReturnQty: null,
                        qbyReturnAmount: null,
                        posReturnQty: null,
                        posReturnAmount: null,
                        posQty: 0,
                        posAmount: "0",
                        sumCostAmount: null,
                        sumReturnCostAmount: null,
                        cleanAmount: null,
                        saleAmount: null,
                        updateTime: null,
                        rpDateStr: "2020-02-22",
                        no: null,
                        name: null,
                        noOrder: null,
                        saleRatio: null,
                        yesterdayAmount: null,
                        yesterdayCostAmount: null,
                        upPosAmount: null,
                        upSaleAmount: null,
                        upCleanAmount: null,
                        upYesterdayAmount: null,
                        upYesterdayCostAmount: null,
                        shopRank: null,
                        studyShop: null,
                        guidanceShop: null,
                        carefulShop: null
                    },
                    {
                        rpShopSaleDataId: null,
                        rpDateTime: "21:00",
                        rpDate: null,
                        shopId: null,
                        qbyQty: 0,
                        qbyAmount: "0",
                        qbyCancelAmount: null,
                        qbyCancelQty: null,
                        qbyReturnQty: null,
                        qbyReturnAmount: null,
                        posReturnQty: null,
                        posReturnAmount: null,
                        posQty: 0,
                        posAmount: "0",
                        sumCostAmount: null,
                        sumReturnCostAmount: null,
                        cleanAmount: null,
                        saleAmount: null,
                        updateTime: null,
                        rpDateStr: "2020-02-22",
                        no: null,
                        name: null,
                        noOrder: null,
                        saleRatio: null,
                        yesterdayAmount: null,
                        yesterdayCostAmount: null,
                        upPosAmount: null,
                        upSaleAmount: null,
                        upCleanAmount: null,
                        upYesterdayAmount: null,
                        upYesterdayCostAmount: null,
                        shopRank: null,
                        studyShop: null,
                        guidanceShop: null,
                        carefulShop: null
                    },
                    {
                        rpShopSaleDataId: null,
                        rpDateTime: "22:00",
                        rpDate: null,
                        shopId: null,
                        qbyQty: 0,
                        qbyAmount: "0",
                        qbyCancelAmount: null,
                        qbyCancelQty: null,
                        qbyReturnQty: null,
                        qbyReturnAmount: null,
                        posReturnQty: null,
                        posReturnAmount: null,
                        posQty: 0,
                        posAmount: "0",
                        sumCostAmount: null,
                        sumReturnCostAmount: null,
                        cleanAmount: null,
                        saleAmount: null,
                        updateTime: null,
                        rpDateStr: "2020-02-22",
                        no: null,
                        name: null,
                        noOrder: null,
                        saleRatio: null,
                        yesterdayAmount: null,
                        yesterdayCostAmount: null,
                        upPosAmount: null,
                        upSaleAmount: null,
                        upCleanAmount: null,
                        upYesterdayAmount: null,
                        upYesterdayCostAmount: null,
                        shopRank: null,
                        studyShop: null,
                        guidanceShop: null,
                        carefulShop: null
                    },
                    {
                        rpShopSaleDataId: null,
                        rpDateTime: "23:00",
                        rpDate: null,
                        shopId: null,
                        qbyQty: 0,
                        qbyAmount: "0",
                        qbyCancelAmount: null,
                        qbyCancelQty: null,
                        qbyReturnQty: null,
                        qbyReturnAmount: null,
                        posReturnQty: null,
                        posReturnAmount: null,
                        posQty: 0,
                        posAmount: "0",
                        sumCostAmount: null,
                        sumReturnCostAmount: null,
                        cleanAmount: null,
                        saleAmount: null,
                        updateTime: null,
                        rpDateStr: "2020-02-22",
                        no: null,
                        name: null,
                        noOrder: null,
                        saleRatio: null,
                        yesterdayAmount: null,
                        yesterdayCostAmount: null,
                        upPosAmount: null,
                        upSaleAmount: null,
                        upCleanAmount: null,
                        upYesterdayAmount: null,
                        upYesterdayCostAmount: null,
                        shopRank: null,
                        studyShop: null,
                        guidanceShop: null,
                        carefulShop: null
                    }
                ]
            },
            httpCode: "0",
            message: null,
            fileDomain: "https://qtltestfiles.oss-cn-shanghai.aliyuncs.com/",
            sessionId: "81B6EBCEA3EEFA15FAD81BCB7037E52A"
        })
    }))
}

/**
 * 获取门店销售表格数据
 * @constructor
 */
export function GetStoreSaleTableData() {
    return new Promise((resolve => {
        resolve({
            result: {
                total: 1,
                everyPage: 1,
                currentPage: 1,
                result: []
            },
            httpCode: "0",
            message: null,
            fileDomain: "https://qtltestfiles.oss-cn-shanghai.aliyuncs.com/",
            sessionId: "81B6EBCEA3EEFA15FAD81BCB7037E52A"
        })
    }))
}

/**
 * 获取门店库存列表数据
 * @constructor
 */
export function GetStoreInventoryList(values) {
    return new Promise((resolve => {
        resolve({
            result: {
                total: 1,
                everyPage: 1,
                currentPage: 1,
                result: [
                    {
                        pdSpuId: 128,
                        pdSkuId: -1,
                        code: "98000",
                        barcode: "98000",
                        pdSpuName: "上海测试商品",
                        pdCategoryName: "喂哺用品",
                        displayName: null,
                        qty: 999,
                        toBPrice: "0.01",
                        waitDeliveryQty: 0,
                        receivingQty: 0,
                        waitReceiveQty: 0,
                        allocateOutWaitingQty: 0,
                        allocateInWaitingQty: 0
                    },
                    {
                        pdSpuId: 93,
                        pdSkuId: 121,
                        code: "111",
                        barcode: "111",
                        pdSpuName: "wy商品很多规格",
                        pdCategoryName: "喂哺用品",
                        displayName: "xs/红色",
                        qty: 798,
                        toBPrice: "111.00",
                        waitDeliveryQty: 0,
                        receivingQty: 0,
                        waitReceiveQty: 0,
                        allocateOutWaitingQty: 0,
                        allocateInWaitingQty: 0
                    },
                    {
                        pdSpuId: 57,
                        pdSkuId: 73,
                        code: null,
                        barcode: null,
                        pdSpuName: "wy仓+门店",
                        pdCategoryName: "孕产系列",
                        displayName: "黄/m",
                        qty: 292,
                        toBPrice: "1.00",
                        waitDeliveryQty: 0,
                        receivingQty: 0,
                        waitReceiveQty: 0,
                        allocateOutWaitingQty: 0,
                        allocateInWaitingQty: 0
                    },
                    {
                        pdSpuId: 136,
                        pdSkuId: 218,
                        code: null,
                        barcode: null,
                        pdSpuName: "wy活动仓库",
                        pdCategoryName: "尿裤湿巾",
                        displayName: "小",
                        qty: 199,
                        toBPrice: "100.00",
                        waitDeliveryQty: 0,
                        receivingQty: 0,
                        waitReceiveQty: 0,
                        allocateOutWaitingQty: 0,
                        allocateInWaitingQty: 0
                    },
                    {
                        pdSpuId: 66,
                        pdSkuId: 91,
                        code: "034403",
                        barcode: "034403",
                        pdSpuName: "xh仓库专用商品",
                        pdCategoryName: "奶粉辅食",
                        displayName: "1000/紫色",
                        qty: 116,
                        toBPrice: "0.01",
                        waitDeliveryQty: 0,
                        receivingQty: 0,
                        waitReceiveQty: 0,
                        allocateOutWaitingQty: 0,
                        allocateInWaitingQty: 0
                    },
                    {
                        pdSpuId: 144,
                        pdSkuId: 234,
                        code: "0908",
                        barcode: "0908",
                        pdSpuName: "xh专区多级满元赠",
                        pdCategoryName: "奶粉辅食",
                        displayName: "灰色",
                        qty: 109,
                        toBPrice: "0.50",
                        waitDeliveryQty: 0,
                        receivingQty: 0,
                        waitReceiveQty: 0,
                        allocateOutWaitingQty: 0,
                        allocateInWaitingQty: 0
                    },
                    {
                        pdSpuId: 144,
                        pdSkuId: 233,
                        code: "0907",
                        barcode: "0907",
                        pdSpuName: "xh专区多级满元赠",
                        pdCategoryName: "奶粉辅食",
                        displayName: "棕色",
                        qty: 101,
                        toBPrice: "0.50",
                        waitDeliveryQty: 0,
                        receivingQty: 0,
                        waitReceiveQty: 0,
                        allocateOutWaitingQty: 0,
                        allocateInWaitingQty: 0
                    },
                    {
                        pdSpuId: 162,
                        pdSkuId: -1,
                        code: "2019112503",
                        barcode: "20191125003",
                        pdSpuName: "jsutin测试44444",
                        pdCategoryName: "其他",
                        displayName: null,
                        qty: 98,
                        toBPrice: "9.00",
                        waitDeliveryQty: 10,
                        receivingQty: 20,
                        waitReceiveQty: 30,
                        allocateOutWaitingQty: 0,
                        allocateInWaitingQty: 0
                    },
                    {
                        pdSpuId: 53,
                        pdSkuId: 64,
                        code: "xh013",
                        barcode: "xh013",
                        pdSpuName: "xh门店多规格",
                        pdCategoryName: "奶粉辅食",
                        displayName: "灰色",
                        qty: 98,
                        toBPrice: "1.00",
                        waitDeliveryQty: 0,
                        receivingQty: 0,
                        waitReceiveQty: 0,
                        allocateOutWaitingQty: 0,
                        allocateInWaitingQty: 0
                    },
                    {
                        pdSpuId: 160,
                        pdSkuId: -1,
                        code: "2019112501",
                        barcode: "20191125001",
                        pdSpuName: "测试Justin 22222",
                        pdCategoryName: "其他",
                        displayName: null,
                        qty: 90,
                        toBPrice: "5.00",
                        waitDeliveryQty: 12,
                        receivingQty: 20,
                        waitReceiveQty: 32,
                        allocateOutWaitingQty: 0,
                        allocateInWaitingQty: 0
                    },
                    {
                        pdSpuId: 161,
                        pdSkuId: -1,
                        code: "2019112502",
                        barcode: "20191125002",
                        pdSpuName: "Justin测试3333",
                        pdCategoryName: "其他",
                        displayName: null,
                        qty: 89,
                        toBPrice: "3.00",
                        waitDeliveryQty: 10,
                        receivingQty: 20,
                        waitReceiveQty: 30,
                        allocateOutWaitingQty: 0,
                        allocateInWaitingQty: 0
                    },
                    {
                        pdSpuId: 16,
                        pdSkuId: -1,
                        code: "xh003",
                        barcode: "xh003",
                        pdSpuName: "xh门店无规格",
                        pdCategoryName: "奶粉辅食",
                        displayName: null,
                        qty: 70,
                        toBPrice: "1.00",
                        waitDeliveryQty: 0,
                        receivingQty: 0,
                        waitReceiveQty: 0,
                        allocateOutWaitingQty: 0,
                        allocateInWaitingQty: 0
                    },
                    {
                        pdSpuId: 52,
                        pdSkuId: 63,
                        code: "04712",
                        barcode: "204712",
                        pdSpuName: "047门店+仓库多规格10-12",
                        pdCategoryName: "安全出行",
                        displayName: "黄",
                        qty: 59,
                        toBPrice: "0.01",
                        waitDeliveryQty: 0,
                        receivingQty: 0,
                        waitReceiveQty: 0,
                        allocateOutWaitingQty: 0,
                        allocateInWaitingQty: 0
                    },
                    {
                        pdSpuId: 134,
                        pdSkuId: 213,
                        code: "07261",
                        barcode: "07261",
                        pdSpuName: "wy活动专用门店",
                        pdCategoryName: "喂哺用品",
                        displayName: "黄",
                        qty: 57,
                        toBPrice: "5.00",
                        waitDeliveryQty: 0,
                        receivingQty: 0,
                        waitReceiveQty: 0,
                        allocateOutWaitingQty: 0,
                        allocateInWaitingQty: 0
                    },
                    {
                        pdSpuId: 45,
                        pdSkuId: 48,
                        code: "04706",
                        barcode: "204706",
                        pdSpuName: "047门店多规格商品双06-07",
                        pdCategoryName: "孕产系列",
                        displayName: "s/小",
                        qty: 55,
                        toBPrice: "0.01",
                        waitDeliveryQty: 0,
                        receivingQty: 0,
                        waitReceiveQty: 0,
                        allocateOutWaitingQty: 0,
                        allocateInWaitingQty: 0
                    }
                ]
            },
            httpCode: "0",
            message: null,
            fileDomain: "https://qtltestfiles.oss-cn-shanghai.aliyuncs.com/",
            sessionId: "81B6EBCEA3EEFA15FAD81BCB7037E52A"
        })
    }))
}

/**
 * 获取门店库存分布列表数据
 * @constructor
 */
export function GetStoreInventoryDistributionList(values) {
    return new Promise((resolve => {
        resolve({
            result: {
                total: 1,
                everyPage: 1,
                currentPage: 1,
                result: [
                    {
                        pdSpuId: 45,
                        pdSkuId: 48,
                        shopName: "Justin",
                        type: null,
                        typeStr: "联营",
                        invQty: 50,
                        provinceId: null,
                        cityId: null,
                        addressCity: "西藏拉萨市"
                    },
                    {
                        pdSpuId: 45,
                        pdSkuId: 48,
                        shopName: "047测试门店",
                        type: null,
                        typeStr: "直营",
                        invQty: 5,
                        provinceId: null,
                        cityId: null,
                        addressCity: "上海上海市"
                    }
                ]
            },
            httpCode: "0",
            message: null,
            fileDomain: "https://qtltestfiles.oss-cn-shanghai.aliyuncs.com/",
            sessionId: "81B6EBCEA3EEFA15FAD81BCB7037E52A"
        })
    }))
}

/**
 * 获取历史库存列表数据
 * @constructor
 */
export function GetHistoryOfInventoryList(values) {
    return new Promise((resolve => {
        resolve({
            result: {
                total: 1,
                everyPage: 1,
                currentPage: 1,
                result: [
                    {
                        pdSpuId: 20826,
                        pdSkuId: -1,
                        code: "20170218001",
                        barcode: "20170218001",
                        pdSpuName: "会员卡",
                        pdCategoryName: "其他",
                        displayName: null,
                        qty: 1006248,
                        toBPrice: "2.00",
                        waitDeliveryQty: 0,
                        receivingQty: 0,
                        waitReceiveQty: 0,
                        allocateOutWaitingQty: 0,
                        allocateInWaitingQty: 0
                    },
                    {
                        pdSpuId: 20800,
                        pdSkuId: 20797,
                        code: "20170506001",
                        barcode: "20170506001",
                        pdSpuName: "qtools兔子吊牌",
                        pdCategoryName: "其他",
                        displayName: "10张",
                        qty: 1000050,
                        toBPrice: "3.00",
                        waitDeliveryQty: 0,
                        receivingQty: 0,
                        waitReceiveQty: 0,
                        allocateOutWaitingQty: 0,
                        allocateInWaitingQty: 0
                    },
                    {
                        pdSpuId: 25219,
                        pdSkuId: -1,
                        code: "20171101001",
                        barcode: "20171101001",
                        pdSpuName: "物流费",
                        pdCategoryName: "其他",
                        displayName: null,
                        qty: 295016,
                        toBPrice: "1.00",
                        waitDeliveryQty: 0,
                        receivingQty: 0,
                        waitReceiveQty: 0,
                        allocateOutWaitingQty: 0,
                        allocateInWaitingQty: 0
                    },
                    {
                        pdSpuId: 29726,
                        pdSkuId: -1,
                        code: "6952837827425",
                        barcode: "6952837827425",
                        pdSpuName: "CTY 皮肤消毒喷雾75%酒精50ml",
                        pdCategoryName: "居家生活",
                        displayName: null,
                        qty: 10765,
                        toBPrice: "15.00",
                        waitDeliveryQty: 0,
                        receivingQty: 0,
                        waitReceiveQty: 0,
                        allocateOutWaitingQty: 0,
                        allocateInWaitingQty: 0
                    },
                    {
                        pdSpuId: 27265,
                        pdSkuId: 31599,
                        code: "7640153868046",
                        barcode: "7640153868046",
                        pdSpuName: "Dana儿童酸奶",
                        pdCategoryName: "奶粉辅食",
                        displayName: "200ml",
                        qty: 9156,
                        toBPrice: "4.00",
                        waitDeliveryQty: 0,
                        receivingQty: 408,
                        waitReceiveQty: 408,
                        allocateOutWaitingQty: 0,
                        allocateInWaitingQty: 0
                    },
                    {
                        pdSpuId: 25768,
                        pdSkuId: 27030,
                        code: "8809019690286",
                        barcode: "8809019690286",
                        pdSpuName: "rayqueen湿巾 便携装*Z",
                        pdCategoryName: "尿裤湿巾",
                        displayName: "20抽薄款",
                        qty: 6982,
                        toBPrice: "7.00",
                        waitDeliveryQty: 0,
                        receivingQty: 620,
                        waitReceiveQty: 620,
                        allocateOutWaitingQty: 0,
                        allocateInWaitingQty: 0
                    },
                    {
                        pdSpuId: 18747,
                        pdSkuId: 18025,
                        code: "8437010580703",
                        barcode: "8437010580703",
                        pdSpuName: "me milk儿童酸酸乳",
                        pdCategoryName: "奶粉辅食",
                        displayName: "草莓味",
                        qty: 5230,
                        toBPrice: "8.00",
                        waitDeliveryQty: 0,
                        receivingQty: 0,
                        waitReceiveQty: 0,
                        allocateOutWaitingQty: 0,
                        allocateInWaitingQty: 0
                    },
                    {
                        pdSpuId: 25768,
                        pdSkuId: 27029,
                        code: "8809019690224",
                        barcode: "8809019690224",
                        pdSpuName: "rayqueen湿巾 便携装*Z",
                        pdCategoryName: "尿裤湿巾",
                        displayName: "20抽厚款",
                        qty: 5228,
                        toBPrice: "8.00",
                        waitDeliveryQty: 0,
                        receivingQty: 360,
                        waitReceiveQty: 360,
                        allocateOutWaitingQty: 0,
                        allocateInWaitingQty: 0
                    },
                    {
                        pdSpuId: 25290,
                        pdSkuId: 26232,
                        code: "8425402065549",
                        barcode: "8425402065549",
                        pdSpuName: "me milk儿童酸酸乳",
                        pdCategoryName: "奶粉辅食",
                        displayName: "蓝莓味/90g",
                        qty: 4663,
                        toBPrice: "8.00",
                        waitDeliveryQty: 0,
                        receivingQty: 72,
                        waitReceiveQty: 72,
                        allocateOutWaitingQty: 0,
                        allocateInWaitingQty: 0
                    },
                    {
                        pdSpuId: 25928,
                        pdSkuId: 27322,
                        code: "8425402065532",
                        barcode: "8425402065532",
                        pdSpuName: "me milk儿童酸酸乳 ",
                        pdCategoryName: "奶粉辅食",
                        displayName: "原味",
                        qty: 4494,
                        toBPrice: "8.00",
                        waitDeliveryQty: 0,
                        receivingQty: 144,
                        waitReceiveQty: 144,
                        allocateOutWaitingQty: 0,
                        allocateInWaitingQty: 0
                    },
                    {
                        pdSpuId: 29717,
                        pdSkuId: 38429,
                        code: "6921829250015",
                        barcode: "6921829250015",
                        pdSpuName: "新净界  口腔消毒喷雾剂",
                        pdCategoryName: "洗护用品",
                        displayName: "儿童款20ml",
                        qty: 3743,
                        toBPrice: "57.50",
                        waitDeliveryQty: 0,
                        receivingQty: 72,
                        waitReceiveQty: 72,
                        allocateOutWaitingQty: 0,
                        allocateInWaitingQty: 0
                    },
                    {
                        pdSpuId: 18747,
                        pdSkuId: 18024,
                        code: "8437010580710",
                        barcode: "8437010580710",
                        pdSpuName: "me milk儿童酸酸乳",
                        pdCategoryName: "奶粉辅食",
                        displayName: "凤梨味",
                        qty: 3588,
                        toBPrice: "8.00",
                        waitDeliveryQty: 0,
                        receivingQty: 126,
                        waitReceiveQty: 126,
                        allocateOutWaitingQty: 0,
                        allocateInWaitingQty: 0
                    },
                    {
                        pdSpuId: 25928,
                        pdSkuId: 31867,
                        code: "8414606541485",
                        barcode: "8414606541485",
                        pdSpuName: "me milk儿童酸酸乳 ",
                        pdCategoryName: "奶粉辅食",
                        displayName: "青苹果味",
                        qty: 3244,
                        toBPrice: "8.00",
                        waitDeliveryQty: 0,
                        receivingQty: 0,
                        waitReceiveQty: 0,
                        allocateOutWaitingQty: 0,
                        allocateInWaitingQty: 0
                    },
                    {
                        pdSpuId: 28947,
                        pdSkuId: -1,
                        code: "20190821001",
                        barcode: "20190821001",
                        pdSpuName: "Qtools果冻包",
                        pdCategoryName: "其他",
                        displayName: null,
                        qty: 3195,
                        toBPrice: "13.00",
                        waitDeliveryQty: 0,
                        receivingQty: 0,
                        waitReceiveQty: 0,
                        allocateOutWaitingQty: 0,
                        allocateInWaitingQty: 0
                    },
                    {
                        pdSpuId: 24676,
                        pdSkuId: 25071,
                        code: "4973728907097",
                        barcode: "4973728907097",
                        pdSpuName: "山口迷你蔬菜手指饼干",
                        pdCategoryName: "奶粉辅食",
                        displayName: "5连包",
                        qty: 3034,
                        toBPrice: "23.00",
                        waitDeliveryQty: 0,
                        receivingQty: 0,
                        waitReceiveQty: 0,
                        allocateOutWaitingQty: 0,
                        allocateInWaitingQty: 0
                    }
                ]
            },
            httpCode: "0",
            message: null,
            fileDomain: "https://qtltestfiles.oss-cn-shanghai.aliyuncs.com/",
            sessionId: "81B6EBCEA3EEFA15FAD81BCB7037E52A"
        })
    }))
}

/**
 * 获取联营分成数据
 * @constructor
 */
export function GetJointOperationShareProportionList(values) {
    return new Promise((resolve => {
        resolve({
            result: {
                total: 1,
                everyPage: 1,
                currentPage: 1,
                result: []
            },
            httpCode: "0",
            message: null,
            fileDomain: "https://qtltestfiles.oss-cn-shanghai.aliyuncs.com/",
            sessionId: "81B6EBCEA3EEFA15FAD81BCB7037E52A"
        })
    }))
}
