const normalOptions=[
  {
    label:'spuCode',
    value:'SPU编码',
    closable:false
  },{
    label:'productName',
    value:'商品名称',
    closable:false
  },{
    label:'skuCode',
    value:'SKU编码',
    closable:false
  },{
    label:'salesAttributeName',
    value:'商品规格',
    closable:false
  },{
    label:'categoryName',
    value:'一级类目',
    closable:true
  },{
    label:'categoryName2',
    value:'二级类目',
    closable:true
  },{
    label:'categoryName3',
    value:'三级类目',
    closable:true
  },{
    label:'categoryName4',
    value:'四级类目',
    closable:true
  },{
    label:'productTypeStr',
    value:'商品类型',
    closable:true
  },{
    label:'brandName',
    value:'品牌',
    closable:true
  },{
    label:'brandAddress',
    value:'品牌归属地',
    closable:true
  },{
    label:"procurementTargetStr",
    value:'采购主体',
    closable:true
  },{
    label:'suitRangeName',
    value:'适用年龄/范围',
    closable:true
  },{
    label:'profitsStr',
    value:'联营分成类型',
    closable:true
  },{
    label:'minBoxSpecification',
    value:'B端销售箱规',
    closable:true
  },{
    label:'sendTypeStr',
    value:'是否代发',
    closable:true
  },{
    label:'isBeforeSalesStr',
    value:'是否预售',
    closable:true
  },{
    label:'isDirectSalesStr',
    value:'是否直邮',
    closable:true
  },{
    label:'batchProcessingStatusStr',
    value:'效期管理',
    closable:true
  },{
    label:'batchProcessingTypeStr',
    value:'效期类型',
    closable:true
  },{
    label:'shelfLife',
    value:'保质期',
    closable:true
  },{
    label:'statusStr',
    value:'SKU审核状态',
    closable:true
  },{
    label:'purchasePrice',
    value:'采购价',
    closable:true
  },{
    label:'businessPrice',
    value:'B端售价',
    closable:true
  },{
    label:'customerPrice',
    value:'C端售价',
    closable:true
  },{
    label:'proposalPrice',
    value:'建议零售价',
    closable:true
  },{
    label:"bonusRate",
    value:'直邮服务费',
    closable:true
  },{
    label:'taxRate',
    value:'税率',
    closable:true
  },{
    label:'createTimeForm',
    value:'SKU创建时间',
    closable:true
  }]
const crossPlainOptions=[
  {
    label:'spuCode',
    value:'SPU编码',
    closable:false
  },{
    label:'productName',
    value:'商品名称',
    closable:false
  },{
    label:'skuCode',
    value:'SKU编码',
    closable:false
  },{
    label:'salesAttributeName',
    value:'商品规格',
    closable:false
  },{
    label:'categoryName',
    value:'一级类目',
    closable:true
  },{
    label:'categoryName2',
    value:'二级类目',
    closable:true
  },{
    label:'categoryName3',
    value:'三级类目',
    closable:true
  },{
    label:'categoryName4',
    value:'四级类目',
    closable:true
  },{
    label:'brandName',
    value:'品牌',
    closable:true
  },{
    label:'brandAddress',
    value:'品牌归属地',
    closable:true
  },{
    label:"bondedWarehouseName",
    value:'保税仓',
    closable:true
  },{
    label:'suitRangeName',
    value:'适用年龄/范围',
    closable:true
  },{
    label:'statusStr',
    value:'SKU审核状态',
    closable:true
  },{
    label:'outerProductCode',
    value:'第三方商品编码',
    closable:true
  },{
    label:'barCode',
    value:'商品条码',
    closable:true
  },{
    label:'purchasePrice',
    value:'purchasePrice',
    closable:true
  },{
    label:'dhPrice',
    value:'出库价',
    closable:true
  },{
    label:'customerPrice',
    value:'C端售价',
    closable:true
  },{
    label:'bonusRate',
    value:'分成比例',
    closable:true
  },{
    label:'taxRate',
    value:'跨境综合税率',
    closable:true
  },{
    label:'createTimeForm',
    value:'SKU创建时间',
    closable:true
  }]
const defautOptions=['spuCode','productName','salesAttributeName','skuCode'];
export  { normalOptions, crossPlainOptions, defautOptions };
