const menu = [{
    "id":"0a4167e8a15a43c1ab9f11ea505f58bf",
    "name":"商品管理",
    "action":"items_manager",
    "cls":null,
    "subActions":[
        {
            "id":"c280e4fa579d4fc4bdf5773ccbcacc1d",
            "name":"基础配置",
            "action":"basic_config",
            "cls":null,
            "subActions":[
                {
                    "id":"62b4f36e9e554357ac59172b0c89f235",
                    "name":"国家地区管理",
                    "action":"country_and_region",
                    "cls":null,
                    "subActions":null
                },{
                    "id":"003a8f4611b343fab41d801c8b3c24c7",
                    "name":"品牌管理",
                    "action":"brand",
                    "cls":null,
                    "subActions":null
                },{
                    "id":"db5c47df7c7a46d087550e196525f9a5",
                    "name":"后台类目管理",
                    "action":"category",
                    "cls":null,
                    "subActions":null
                },{
                    "id":"b7b8cf70d24f45b4a2b492e586479cad",
                    "name":"规格管理",
                    "action":"standards",
                    "cls":null,
                    "subActions":null
                }
            ]
        },{
            "id":"634d4d410fc04e50a5dcf2e0177c761d",
            "name":"基础商品",
            "action":"basic_items",
            "cls":null,
            "subActions":[
                {
                    "id":"7f9e38cdc4fa4d539b728147cc6fcbc1",
                    "name":"商品审核",
                    "action":"items_examine",
                    "cls":null,
                    "subActions":null
                }
            ]
        },{
            "id":"1",
            "name":"B端商品",
            "action":"bGoods",
            "cls":null,
        }]
    },{
        "id":"e3193c89076a443fa694bb85901062a1",
        "name":"仓库管理",
        "action":"stock",
        "cls":"fa-shopping-bag",
        "subActions":[
            {
                "id":"18130687f4484524bbcd99c9896cc716",
                "name":"仓库管理",
                "action":"wareHouseManage",
                "cls":"fa",
                "subActions":null
            },{
                "id":"16e29880c6da4650ba491c49518cfef0",
                "name":"库存管理",
                "action":"stockManage",
                "cls":"fa","subActions":null
            }
        ]
    },{
        "id":"64fb893e1b414447a5e46e6b0b951b07",
        "name":"订单管理",
        "action":"orders",
        "cls":"fa-th-large",
        "subActions":[{
            "id":"2de380f40c4a4f2bb92de380ab421ce8",
            "name":"销售订单查询",
            "action":"orderSale",
            "cls":"fa",
            "subActions":null
        },{
            "id":"3695ff5b770e4d00bdf0fa02c1a6e10b",
            "name":"掌柜订单查询",
            "action":"orderShopkeeper",
            "cls":"fa",
            "subActions":null
        },{
            "id":"3920549025014371a7ee5d40c28ef6e1",
            "name":"POS订单查询",
            "action":"orderPos",
            "cls":"fa",
            "subActions":null
        },{
            "id":"3e99c49fd7934583b7226f5968ba9168",
            "name":"线上订单查询",
            "action":"orderOnline",
            "cls":"fa",
            "subActions":null
        },{
            "id":"4163ec9ca9904e94a5f748efa6cae652",
            "name":"保税订单查询",
            "action":"orderBonded",
            "cls":"fa",
            "subActions":null
        },{
            "id":"419bc1897a144f8a9851360ce98fd96b",
            "name":"订单代发",
            "action":"orderAgency",
            "cls":"fa",
            "subActions":null
        },{
            "id":"51ee9bdd81c5409bbf60f85aa86c9f0c",
            "name":"待确认订单",
            "action":"orderConfirm",
            "cls":"fa",
            "subActions":null
        }
    ]},{
        "id":"9966b88e51384bfca2a087f1aab62f3e",
        "name":"合作中心",
        "action":"center",
        "cls":"fa-headphones",
        "subActions":[
            {
                "id":"ae9b4fc73d964fa8a99e9a880dae7720",
                "name":"门店管理",
                "action":"channel",
                "cls":"fa",
                "subActions":null
            },{
                "id":"436f0e3684b146de8fae47d538e349d6",
                "name":"供应商管理",
                "action":"supplier",
                "cls":"fa",
                "subActions":null
            },{
                "id":"d3d9adcff3cf416ca4e19762859e53b5",
                "name":"招商管理",
                "action":"customer",
                "cls":"fa",
                "subActions":null
            }
        ]
    }
]
export default menu;